export const cards = [
	{
		accName: 'Nexus',
		accType: 'Debit Account',
		costMonth: 'Start Free',
		costAnn: 'Start Free',
		billMonth: '',
		billAnn: '',
		detailsFirst: [
			'Cash Back',
			'Deposit Flexibility (ACH, Wire, Direct Deposit,Peer-to-Peer Transfer)',
			'Access Funds Globally 24 x 7 x 365',
			'Free High Quality Recycled Ocean Bound Plastic Visa Debit Card',
			'Earn Cash Back for Every Purchase',
		],
		detailsSecond: [
			'Zero-Fee ATM Network',
			'Round Up Transactions to the Nearest Dollar to Donate to Good Causes or Increase Yield on your Orbit or Odyssey Account.',
			'Deposits Insured up to $2,000,000 Through Standard FDIC Insurance and Yield FDIC Extended Coverage Program with Participating FDIC Bank Partners',
		],
		addon: '',
	},
	{
		accName: 'Reserve',
		accType: 'Interest Bearing Account APY',
		costMonth: '$9.99',
		costAnn: '$88.99',
		billMonth: 'Billed Monthly',
		billAnn: 'Billed Annually',
		detailsFirst: [
			'3.5% APY',
			'Deposit Flexibility (ACH, Wire, Direct Deposit, Peer-to-Peer Transfer)',
			'Access Funds Globally 24 x 7 x 365',
			'Earn Double Cash Back for Every Purchase',
			'Round Up Transactions to the Nearest Dollar to Donate to Good Causes or Increase Yield on your Orbit or Odyssey Account!',
		],
		detailsSecond: [
			'Zero-Fee ATM Network',
			'2% Closing Cost Credit on any Mortgage Loan with Yield Mortgage',
			'Deposits Insured up to $2,000,000 Through Standard FDIC Insurance and Yield FDIC Extended Coverage Program with Participating FDIC Bank Partners',
		],
		addon: '',
	},
	{
		accName: 'Horizon',
		accType: 'Interest Bearing Account APY',
		costMonth: '$16.99',
		costAnn: '$150',
		billMonth: 'Billed Monthly',
		billAnn: 'Billed Annually',
		detailsFirst: [
			'5% APY',
			'Deposit Flexibility (ACH, Wire, Direct Deposit, Peer-to-Peer Transfer)',
			'Access Funds Globally 24 x 7 x 365',
			'Free Elite Metal Visa Debit Card',
			'Zero-Fee ATM Network',
			'Earn Double Cash Back for Every Purchase',
			'Round Up Transactions to the Nearest Dollar to Donate to Good Causes or Increase Yield on your Orbit or Odyssey Account!',
		],
		detailsSecond: [
			'2% Closing Cost Credit  on any Mortgage Loan with Yield Mortgage',
			'One Account, Multiple Currencies - Store up to 19 Currencies',
			'Fee-Free international payments via Yield Money',
			'Minimum 50% Discount on All Crypto Purchases on Yield Crypto Wallet and up to 75% Discount Depending on Monthly Transaction Volume',
			'Deposits Insured up to $2,000,000 Through Standard FDIC Insurance and Yield FDIC Extended Coverage Program with Participating FDIC Bank Partners',
		],
		addon: '',
	},
	{
		accName: 'Orbit',
		accType: 'The Super High Yield Term Deposit',
		costMonth: 'Zero Cost',
		costAnn: 'Zero Cost',
		billMonth: '',
		billAnn: '',
		detailsFirst: [
			'5.5% APY to 9.5% APY Depending on Interest Distributions & Term Length(s) Selected.',
			'Deposit Flexibility (ACH, Wire, Direct Deposit, Peer-to-Peer Transfer)',
			'2% Closing Cost Credit on any Mortgage Loan with Yield Mortgage',
			'Fee-Free international payments via Yield Money',
			'Yield Member Lounge Access',
			'Discounted Private Air Travel',
		],
		detailsSecond: [
			'Discounted Yacht Rental',
			'Minimum 50% Discount on All Crypto Purchases on Yield Crypto Wallet and up to 75% Discount Depending on Monthly Transaction Volume',
			"Deposits Insured up to $10,000,000 Through Yield's Depository Network of AM Best Top Rated Insurers",
		],
		addon:
			'**14% APY offered when selecting full term option which does not allow any interest distribution until full maturity of term deposit.',
	},
	{
		accName: 'Odyssey',
		accType: 'THE MEGA HIGH-YIELD TERM DEPOSIT',
		costMonth: 'Zero Cost',
		costAnn: 'Zero Cost',
		billMonth: '',
		billAnn: '',
		detailsFirst: [
			'6.5% APY to 10.5% APY Depending on Interest Distributions & Term length(s) Selected.',
			'Deposit Flexibility (ACH, Wire, Direct Deposit, Peer-to-Peer, Transfer)',
			'2% Closing Cost Credit on any Mortgage Loan with Yield Mortgage',
			'Fee-Free international payments via Yield Money',
			'Yield Member Lounge Access',
			'Discounted Private Air Travel',
		],
		detailsSecond: [
			'Discounted Yacht Rental',
			'Minimum 50% Discount on All Crypto Purchases on Yield Crypto Wallet and up to 75% Discount Depending on Monthly Transaction Volume',
			"Deposits Insured up to $10,000,000 Through Yield's Depository Network of AM Best Top Rated Insurers",
		],
		addon:
			'**15% APY offered when selecting full term option which does not allow any interest distribution until full maturity of term deposit.',
	},
];
